#! /usr/bin/python3
import os
import random
import sys


home = os.getenv("HOME")
PATH_TO_DICT = home + '/CEL/dict/'
PATH_TO_CONFIG = home + '/CEL/conf/conf.txt'

def get_dict():
    with open(PATH_TO_CONFIG) as f:
        confs = f.readlines()
    confs = [x.strip() for x in confs]
    dictname = confs[0].split()
    return dictname[1]

def config():
    dict = get_dict()
    print('Now you use', dict)
    print('You can change the dictionary or create a new one. Write a name of the dictionary or New')
    cmd = 'ls ' + PATH_TO_DICT
    os.system(cmd)
    print('New')
    cmd = str(input())
    file = ''
    if (cmd == 'New'):
        name = str(input('Enter the name of the dictionary: '))
        tmp = name
        name = PATH_TO_DICT + name
        k = 'touch '+ name
        k = k.replace(';', '')
        k = k.replace('&', '')
        os.system(k)
        dict = tmp
    elif (os.path.isfile(PATH_TO_DICT+cmd)):
        dict = cmd
    else:
        print('Wrong name of the dictionary')
        return
    conf_dict = 'conf ' + dict
    with open(PATH_TO_CONFIG, 'w') as file: file.writelines(conf_dict)
    print('Dictionary changed successfully')
    

def print_word(word):
    n = len(word)
    up = n + 4
    low = up
    up_str = '='*up
    midle_str = '= ' + word + ' ='
    low_str = '='*low
    print(up_str)
    print(midle_str)
    print(low_str)

def choose_topic():
    print("Choose the dictionary you need:")
    cmd = 'ls ' + PATH_TO_DICT
    os.system(cmd)
    dict = str(input())
    dict_with_path = PATH_TO_DICT + dict
    if (os.path.isfile(dict_with_path)):
        return dict
    else:
        return "none"

def get_wordlist(dict):
    with open(dict) as f:
        wordlist = f.readlines()
    wordlist = [x.strip() for x in wordlist]
    return wordlist

def simple_mode():
    dict = get_dict()
    link = PATH_TO_DICT + dict
    words = get_wordlist(link) 
    random.shuffle(words)
    for word in words:
        pair = word.split("@")
        eng = pair[0]
        rus = pair[1]
        print_word(rus)
        s = input()
        print_word(eng)
        s = input()
        os.system('clear')

def add_new_word():
    from deep_translator import GoogleTranslator
    dict = get_dict()
    file = PATH_TO_DICT + dict
    print('Now you use:', dict)
    eng = str(input("Enter English word: "))
    rus = GoogleTranslator(source='auto', target='ru').translate(eng)
    print_word(rus)
    sub = str(input('Save word and translation?(y/n): '))
    if(sub == 'y'):
        line = eng + '@' + rus + '\n'
        with open(file, 'a') as file: file.writelines(line) 
    
def help():
    print('Use:')
    print('CEL [options]')
    print('-a, --add    - add a new word')
    print('-s, --start  - start repeating words')
    print('--conf       - change the dictionary')


if __name__ == '__main__':
    if(len(sys.argv) > 1):
        if(sys.argv[1] == '--add' or sys.argv[1] == '-a'):
            add_new_word()
        elif(sys.argv[1] == '--start' or sys.argv[1] == '-s'):
            simple_mode()
        elif(sys.argv[1] == '--conf'):
            config()
        else:
            help()
    else:
        help()

    




